### PR TITLE
bugfix: geopoint data needs to be checked before doc ref

### PR DESCRIPTION
**Pull request by andraus**
Hello,

I fixed a bug that occurred when backing up geopoint values.

DocumentReference was being checked before geopoint and was failing due to an undefined type property. Checking geopoint first fixes the issue.

Thanks and  regards,

### CODE REVIEW

**Comment by willhlaw** [comment]
Thanks for the fix. However, the changes should be made to the `/lib/FirestoreDocument.js` [here](https://github.com/willhlaw/node-firestore-backup-restore/commit/3e71d39fb1ea207abe7c5f55806b896f2137c833#diff-d30f708b36ba5313f004b7f9da8b45d5R241) around line 241 instead of the build file. 

Once the change is made to the source file under `/lib`, then run `yarn build` or `npm build` to re-create the `/build` folder.

**Comment by andraus** [comment]
Thanks for the heads up. I just pushed a new commit for the correct file. The first commit, for the file under `/build`, isn't changed because `yarn build` produces exactly he same output as the change that I made manually, as it should.

**Review by willhlaw — APPROVED** [review]
Ok, looks good. Thanks!

**Comment by willhlaw** [comment]
Just published patch to npm as 1.3.1.

**Pull request merged**
